
export function lookupID(id:number) {
  for (var x in teltonicaIoElements) {
    if (parseInt(teltonicaIoElements[x].id) == id) {
      return teltonicaIoElements[x];
    }
  }
}

export var teltonicaIoElements = [
  {
    "id": "239",
    "propname": "Ignition",
    "bytes": "1",
    "type": "Unsigned",
    "min": "0",
    "max": "1",
    "multiplier": "",
    "units": "",
    "description": "Logic: 0/1 (depends on Ignition source)",
    "hw": "All",
    "category": "Permanent"
  },
  {
    "id": "240",
    "propname": "Movement",
    "bytes": "1",
    "type": "Unsigned",
    "min": "0",
    "max": "1",
    "multiplier": "",
    "units": "",
    "description": "Logic: 0/1 (depends on Movement source)",
    "hw": "All",
    "category": "Permanent"
  },
  {
    "id": "80",
    "propname": "Data Mode",
    "bytes": "1",
    "type": "Unsigned",
    "min": "0",
    "max": "5",
    "multiplier": "",
    "units": "",
    "description": "0 – Home On Stop1 – Home On Moving2 – Roaming On Stop3 – Roaming On Moving4 – Unknown On Stop5 – Unknown On Moving",
    "hw": "All",
    "category": "Permanent"
  },
  {
    "id": "21",
    "propname": "GSM Signal",
    "bytes": "1",
    "type": "Unsigned",
    "min": "0",
    "max": "5",
    "multiplier": "",
    "units": "",
    "description": "Value in range 1-5",
    "hw": "All",
    "category": "Permanent"
  },
  {
    "id": "200",
    "propname": "Sleep Mode",
    "bytes": "1",
    "type": "Unsigned",
    "min": "0",
    "max": "2",
    "multiplier": "",
    "units": "",
    "description": "0 – No Sleep 1 – GPS Sleep 2 – Deep Sleep 3 – Online Sleep",
    "hw": "All",
    "category": "Permanent"
  },
  {
    "id": "69",
    "propname": "GNSS Status",
    "bytes": "1",
    "type": "Unsigned",
    "min": "0",
    "max": "3",
    "multiplier": "",
    "units": "",
    "description": "0 – OFF 1 - ON with fix 2 - ON without fix 3 - In sleep state",
    "hw": "All",
    "category": "Permanent"
  },
  {
    "id": "181",
    "propname": "GNSS PDOP",
    "bytes": "2",
    "type": "Unsigned",
    "min": "0",
    "max": "500",
    "multiplier": "0.1",
    "units": "",
    "description": "Probability",
    "hw": "All",
    "category": "Permanent"
  },
  {
    "id": "182",
    "propname": "GNSS HDOP",
    "bytes": "2",
    "type": "Unsigned",
    "min": "0",
    "max": "500",
    "multiplier": "0.1",
    "units": "",
    "description": "Probability",
    "hw": "All",
    "category": "Permanent"
  },
  {
    "id": "66",
    "propname": "External Voltage",
    "bytes": "2",
    "type": "Unsigned",
    "min": "0",
    "max": "65535",
    "multiplier": "",
    "units": "mV",
    "description": "Voltage mV",
    "hw": "All",
    "category": "Permanent"
  },
  {
    "id": "24",
    "propname": "Speed",
    "bytes": "2",
    "type": "Unsigned",
    "min": "0",
    "max": "350",
    "multiplier": "",
    "units": "km/h",
    "description": "Value km/h",
    "hw": "All",
    "category": "Permanent"
  },
  {
    "id": "205",
    "propname": "GSM Cell ID",
    "bytes": "2",
    "type": "Unsigned",
    "min": "0",
    "max": "65535",
    "multiplier": "",
    "units": "",
    "description": "GSM base station ID",
    "hw": "All",
    "category": "Permanent"
  },
  {
    "id": "206",
    "propname": "GSM Area Code",
    "bytes": "2",
    "type": "Unsigned",
    "min": "0",
    "max": "65535",
    "multiplier": "",
    "units": "",
    "description": "Location Area code (LAC) it depends on GSM operator. It provides unique number which assigned to a set of base GSM Stations. Max value: 65536",
    "hw": "All",
    "category": "Permanent"
  },
  {
    "id": "67",
    "propname": "Battery Voltage",
    "bytes": "2",
    "type": "Unsigned",
    "min": "0",
    "max": "65535",
    "multiplier": "",
    "units": "mV",
    "description": "Voltage mV",
    "hw": "All",
    "category": "Permanent"
  },
  {
    "id": "68",
    "propname": "Battery Current",
    "bytes": "2",
    "type": "Unsigned",
    "min": "0",
    "max": "65535",
    "multiplier": "",
    "units": "mA",
    "description": "Current mA",
    "hw": "All",
    "category": "Permanent"
  },
  {
    "id": "241",
    "propname": "Active GSM Operator",
    "bytes": "4",
    "type": "Unsigned",
    "min": "0",
    "max": "4294967295",
    "multiplier": "",
    "units": "",
    "description": "Currently used GSM Operator code",
    "hw": "All",
    "category": "Permanent"
  },
  {
    "id": "199",
    "propname": "Trip Odometer",
    "bytes": "4",
    "type": "Unsigned",
    "min": "0",
    "max": "4294967295",
    "multiplier": "",
    "units": "mA",
    "description": "Trip Odometer value in meters",
    "hw": "All",
    "category": "Permanent"
  },
  {
    "id": "16",
    "propname": "Total Odometer",
    "bytes": "4",
    "type": "Unsigned",
    "min": "0",
    "max": "4294967295",
    "multiplier": "",
    "units": "m",
    "description": "Total Odometer value in meters",
    "hw": "All",
    "category": "Permanent"
  },
  {
    "id": "1",
    "propname": "Digital Input 1",
    "bytes": "1",
    "type": "Unsigned",
    "min": "0",
    "max": "1",
    "multiplier": "",
    "units": "",
    "description": "Logic: 0/1",
    "hw": "All",
    "category": "Permanent"
  },
  {
    "id": "9",
    "propname": "Analog input 1",
    "bytes": "2",
    "type": "Unsigned",
    "min": "0",
    "max": "65535",
    "multiplier": "",
    "units": "mV",
    "description": "Voltage mV",
    "hw": "All",
    "category": "Permanent"
  },
  {
    "id": "179",
    "propname": "Digital Output 1",
    "bytes": "1",
    "type": "Unsigned",
    "min": "0",
    "max": "1",
    "multiplier": "",
    "units": "",
    "description": "Logic: 0/1",
    "hw": "FMB202 FMB204 FMB206",
    "category": "Permanent"
  },
  {
    "id": "12",
    "propname": "Fuel Used GPS",
    "bytes": "4",
    "type": "Unsigned",
    "min": "0",
    "max": "4294967295",
    "multiplier": "",
    "units": "ml",
    "description": "Fuel Used ml",
    "hw": "All",
    "category": "Permanent"
  },
  {
    "id": "13",
    "propname": "Fuel Rate GPS",
    "bytes": "2",
    "type": "Unsigned",
    "min": "0",
    "max": "32767",
    "multiplier": "100",
    "units": "l/h *100",
    "description": "Average Fuel Use l/h",
    "hw": "All",
    "category": "Permanent"
  },
  {
    "id": "17",
    "propname": "Asis X",
    "bytes": "2",
    "type": "Signed",
    "min": "-8000",
    "max": "8000",
    "multiplier": "",
    "units": "mG",
    "description": "X axis value mG",
    "hw": "All",
    "category": "Permanent"
  },
  {
    "id": "18",
    "propname": "Asis Y",
    "bytes": "2",
    "type": "Signed",
    "min": "-8000",
    "max": "8000",
    "multiplier": "",
    "units": "mG",
    "description": "Y axis value mG",
    "hw": "All",
    "category": "Permanent"
  },
  {
    "id": "19",
    "propname": "Asis Z",
    "bytes": "2",
    "type": "Signed",
    "min": "-8000",
    "max": "8000",
    "multiplier": "",
    "units": "mG",
    "description": "Z axis value mG",
    "hw": "All",
    "category": "Permanent"
  },
  {
    "id": "11",
    "propname": "ICCID",
    "bytes": "8",
    "type": "Unsigned",
    "min": "0",
    "max": "0xffffffffffffffff",
    "multiplier": "",
    "units": "",
    "description": "Value of SIM ICCID",
    "hw": "All",
    "category": "Permanent"
  },
  {
    "id": "10",
    "propname": "SD Status",
    "bytes": "1",
    "type": "Unsigned",
    "min": "0",
    "max": "1",
    "multiplier": "",
    "units": "",
    "description": "Logic: 0 – not present 1 – present",
    "hw": "All",
    "category": "Permanent"
  },
  {
    "id": "2",
    "propname": "Digital Input 2",
    "bytes": "1",
    "type": "Unsigned",
    "min": "0",
    "max": "1",
    "multiplier": "",
    "units": "",
    "description": "Logic: 0/1",
    "hw": "All",
    "category": "Permanent"
  },
  {
    "id": "3",
    "propname": "Digital Input 3",
    "bytes": "1",
    "type": "Unsigned",
    "min": "0",
    "max": "1",
    "multiplier": "",
    "units": "",
    "description": "Logic: 0/1",
    "hw": "All",
    "category": "Permanent"
  },
  {
    "id": "261",
    "propname": "Digital Input 4",
    "bytes": "1",
    "type": "Unsigned",
    "min": "0",
    "max": "1",
    "multiplier": "",
    "units": "",
    "description": "Logic: 0/1",
    "hw": "FMB207",
    "category": "Permanent"
  },
  {
    "id": "6",
    "propname": "Analog input 2",
    "bytes": "2",
    "type": "Unsigned",
    "min": "0",
    "max": "65535",
    "multiplier": "",
    "units": "mV",
    "description": "Voltage mV",
    "hw": "FMB207",
    "category": "Permanent"
  },
  {
    "id": "180",
    "propname": "Digital Output 2",
    "bytes": "1",
    "type": "Unsigned",
    "min": "0",
    "max": "1",
    "multiplier": "",
    "units": "",
    "description": "Logic: 0/1",
    "hw": "FMB202 FMB204 FMB206",
    "category": "Permanent"
  },
  {
    "id": "72",
    "propname": "Dallas Temperature 1",
    "bytes": "4",
    "type": "Signed",
    "min": "-550",
    "max": "1150",
    "multiplier": "0.1",
    "units": "°C",
    "description": "Degrees ( °C ) -55 - +115 if 3000 – Dallas error",
    "hw": "FMB202 FMB204 FMB206",
    "category": "Permanent"
  },
  {
    "id": "73",
    "propname": "Dallas Temperature 2",
    "bytes": "4",
    "type": "Signed",
    "min": "-550",
    "max": "1150",
    "multiplier": "0.1",
    "units": "°C",
    "description": "Degrees ( °C ) -55 - +115 if 3000 – Dallas error",
    "hw": "FMB202 FMB204 FMB206",
    "category": "Permanent"
  },
  {
    "id": "74",
    "propname": "Dallas Temperature 3",
    "bytes": "4",
    "type": "Signed",
    "min": "-550",
    "max": "1150",
    "multiplier": "0.1",
    "units": "°C",
    "description": "Degrees ( °C ) -55 - +115 if 3000 – Dallas error",
    "hw": "FMB202 FMB204 FMB206",
    "category": "Permanent"
  },
  {
    "id": "75",
    "propname": "Dallas Temperature 4",
    "bytes": "4",
    "type": "Signed",
    "min": "-550",
    "max": "1150",
    "multiplier": "0.1",
    "units": "°C",
    "description": "Degrees ( °C ) -55 - +115 if 3000 – Dallas error",
    "hw": "FMB202 FMB204 FMB206",
    "category": "Permanent"
  },
  {
    "id": "76",
    "propname": "Dallas Temperature ID 1",
    "bytes": "8",
    "type": "Unsigned",
    "min": "0",
    "max": "0xffffffffffffffff",
    "multiplier": "",
    "units": "",
    "description": "Dallas sensor ID",
    "hw": "FMB202 FMB204 FMB206",
    "category": "Permanent"
  },
  {
    "id": "77",
    "propname": "Dallas Temperature ID 2",
    "bytes": "8",
    "type": "Unsigned",
    "min": "0",
    "max": "0xffffffffffffffff",
    "multiplier": "",
    "units": "",
    "description": "Dallas sensor ID",
    "hw": "FMB202 FMB204 FMB206",
    "category": "Permanent"
  },
  {
    "id": "79",
    "propname": "Dallas Temperature ID 3",
    "bytes": "8",
    "type": "Unsigned",
    "min": "0",
    "max": "0xffffffffffffffff",
    "multiplier": "",
    "units": "",
    "description": "Dallas sensor ID",
    "hw": "FMB202 FMB204 FMB206",
    "category": "Permanent"
  },
  {
    "id": "71",
    "propname": "Dallas Temperature ID 4",
    "bytes": "8",
    "type": "Unsigned",
    "min": "0",
    "max": "0xffffffffffffffff",
    "multiplier": "",
    "units": "",
    "description": "Dallas sensor ID",
    "hw": "FMB202 FMB204 FMB206",
    "category": "Permanent"
  },
  {
    "id": "78",
    "propname": "iButton",
    "bytes": "8",
    "type": "Unsigned",
    "min": "0",
    "max": "0xffffffffffffffff",
    "multiplier": "",
    "units": "",
    "description": "iButton ID",
    "hw": "FMB202 FMB204 FMB206",
    "category": "Permanent"
  },
  {
    "id": "207",
    "propname": "RFID",
    "bytes": "8",
    "type": "Unsigned",
    "min": "0",
    "max": "0xffffffffffffffff",
    "multiplier": "",
    "units": "",
    "description": "RFID ID",
    "hw": "FMB207",
    "category": "Permanent"
  },
  {
    "id": "201",
    "propname": "LLS Fuel 1",
    "bytes": "2",
    "type": "Unsigned",
    "min": "0",
    "max": "65535",
    "multiplier": "",
    "units": "kvants or ltr",
    "description": "Fuel level measured by LLS sensor via RS232 in kvants or liters",
    "hw": "FMB207",
    "category": "Permanent"
  },
  {
    "id": "202",
    "propname": "LLS Temperature 1",
    "bytes": "1",
    "type": "Signed",
    "min": "-128",
    "max": "127",
    "multiplier": "",
    "units": "°C",
    "description": "Fuel temperature measured by LLS via RS232 in degrees Celsius",
    "hw": "FMB207",
    "category": "Permanent"
  },
  {
    "id": "203",
    "propname": "LLS Fuel 2",
    "bytes": "2",
    "type": "Unsigned",
    "min": "0",
    "max": "65535",
    "multiplier": "",
    "units": "kvants or ltr",
    "description": "Fuel level measured by LLS sensor via RS232 in kvants or liters",
    "hw": "FMB207",
    "category": "Permanent"
  },
  {
    "id": "204",
    "propname": "LLS Temperature 2",
    "bytes": "1",
    "type": "Signed",
    "min": "-128",
    "max": "127",
    "multiplier": "",
    "units": "°C",
    "description": "Fuel temperature measured by LLS via RS232 in degrees Celsius",
    "hw": "FMB207",
    "category": "Permanent"
  },
  {
    "id": "210",
    "propname": "LLS Fuel 3",
    "bytes": "2",
    "type": "Unsigned",
    "min": "0",
    "max": "65535",
    "multiplier": "",
    "units": "kvants or ltr",
    "description": "Fuel level measured by LLS sensor via RS232 in kvants or liters",
    "hw": "FMB207",
    "category": "Permanent"
  },
  {
    "id": "211",
    "propname": "LLS Temperature 3",
    "bytes": "1",
    "type": "Signed",
    "min": "-128",
    "max": "127",
    "multiplier": "",
    "units": "°C",
    "description": "Fuel temperature measured by LLS via RS232 in degrees Celsius",
    "hw": "FMB207",
    "category": "Permanent"
  },
  {
    "id": "212",
    "propname": "LLS Fuel 4",
    "bytes": "2",
    "type": "Unsigned",
    "min": "0",
    "max": "65535",
    "multiplier": "",
    "units": "kvants or ltr",
    "description": "Fuel level measured by LLS sensor via RS232 in kvants or liters",
    "hw": "FMB207",
    "category": "Permanent"
  },
  {
    "id": "213",
    "propname": "LLS Temperature 4",
    "bytes": "1",
    "type": "Signed",
    "min": "-128",
    "max": "127",
    "multiplier": "",
    "units": "°C",
    "description": "Fuel temperature measured by LLS via RS232 in degrees Celsius",
    "hw": "FMB207",
    "category": "Permanent"
  },
  {
    "id": "214",
    "propname": "LLS Fuel 5",
    "bytes": "2",
    "type": "Unsigned",
    "min": "0",
    "max": "65535",
    "multiplier": "",
    "units": "kvants or ltr",
    "description": "Fuel level measured by LLS sensor via RS232 in kvants or liters",
    "hw": "FMB207",
    "category": "Permanent"
  },
  {
    "id": "215",
    "propname": "LLS Temperature 5",
    "bytes": "1",
    "type": "Signed",
    "min": "-128",
    "max": "127",
    "multiplier": "",
    "units": "°C",
    "description": "Fuel temperature measured by LLS via RS232 in degrees Celsius",
    "hw": "FMB207",
    "category": "Permanent"
  },
  {
    "id": "15",
    "propname": "Eco Score",
    "bytes": "2",
    "type": "Unsigned",
    "min": "0",
    "max": "65535",
    "multiplier": "0.01",
    "units": "",
    "description": "Average amount of events on some distance",
    "hw": "All",
    "category": "Permanent"
  },
  {
    "id": "238",
    "propname": "User ID",
    "bytes": "8",
    "type": "Unsigned",
    "min": "0",
    "max": "0xffffffffffffffff",
    "multiplier": "",
    "units": "",
    "description": "MAC address of NMEA receiver device connected via Bluetooth",
    "hw": "All",
    "category": "Permanent"
  },
  {
    "id": "25",
    "propname": "BLE Temperature #1",
    "bytes": "2",
    "type": "Signed",
    "min": "-400",
    "max": "1250",
    "multiplier": "0.1",
    "units": "°C",
    "description": "Degrees ( °C ) -40 - +125; Error codes: 4000 – abnormal sensor state 3000 – sensor not found 2000 – failed sensor data parsing",
    "hw": "All",
    "category": "Permanent"
  },
  {
    "id": "26",
    "propname": "BLE Temperature #2",
    "bytes": "2",
    "type": "Signed",
    "min": "-400",
    "max": "1250",
    "multiplier": "0.1",
    "units": "°C",
    "description": "Degrees ( °C ) -40 - +125; Error codes: 4000 – abnormal sensor state 3000 – sensor not found 2000 – failed sensor data parsing",
    "hw": "All",
    "category": "Permanent"
  },
  {
    "id": "27",
    "propname": "BLE Temperature #3",
    "bytes": "2",
    "type": "Signed",
    "min": "-400",
    "max": "1250",
    "multiplier": "0.1",
    "units": "°C",
    "description": "Degrees ( °C ) -40 - +125; Error codes: 4000 – abnormal sensor state 3000 – sensor not found 2000 – failed sensor data parsing",
    "hw": "All",
    "category": "Permanent"
  },
  {
    "id": "28",
    "propname": "BLE Temperature #4",
    "bytes": "2",
    "type": "Signed",
    "min": "-400",
    "max": "1250",
    "multiplier": "0.1",
    "units": "°C",
    "description": "Degrees ( °C ) -40 - +125; Error codes: 4000 – abnormal sensor state 3000 – sensor not found 2000 – failed sensor data parsing",
    "hw": "All",
    "category": "Permanent"
  },
  {
    "id": "29",
    "propname": "BLE Battery voltage #1",
    "bytes": "1",
    "type": "Unsigned",
    "min": "0",
    "max": "100",
    "multiplier": "",
    "units": "%",
    "description": "Battery voltage of sensor #1",
    "hw": "All",
    "category": "Permanent"
  },
  {
    "id": "20",
    "propname": "BLE Battery voltage #2",
    "bytes": "1",
    "type": "Unsigned",
    "min": "0",
    "max": "100",
    "multiplier": "",
    "units": "%",
    "description": "Battery voltage of sensor #2",
    "hw": "All",
    "category": "Permanent"
  },
  {
    "id": "22",
    "propname": "BLE Battery voltage #3",
    "bytes": "1",
    "type": "Unsigned",
    "min": "0",
    "max": "100",
    "multiplier": "",
    "units": "%",
    "description": "Battery voltage of sensor #3",
    "hw": "All",
    "category": "Permanent"
  },
  {
    "id": "23",
    "propname": "BLE Battery voltage #4",
    "bytes": "1",
    "type": "Unsigned",
    "min": "0",
    "max": "100",
    "multiplier": "",
    "units": "%",
    "description": "Battery voltage of sensor #4",
    "hw": "All",
    "category": "Permanent"
  },
  {
    "id": "86",
    "propname": "BLE Humidity #1",
    "bytes": "2",
    "type": "Unsigned",
    "min": "0",
    "max": "1000",
    "multiplier": "0.1",
    "units": "%RH",
    "description": "",
    "hw": "All",
    "category": "Permanent"
  },
  {
    "id": "104",
    "propname": "BLE Humidity #2",
    "bytes": "2",
    "type": "Unsigned",
    "min": "0",
    "max": "1000",
    "multiplier": "0.1",
    "units": "%RH",
    "description": "",
    "hw": "All",
    "category": "Permanent"
  },
  {
    "id": "106",
    "propname": "BLE Humidity #3",
    "bytes": "2",
    "type": "Unsigned",
    "min": "0",
    "max": "1000",
    "multiplier": "0.1",
    "units": "%RH",
    "description": "",
    "hw": "All",
    "category": "Permanent"
  },
  {
    "id": "108",
    "propname": "BLE Humidity #4",
    "bytes": "2",
    "type": "Unsigned",
    "min": "0",
    "max": "1000",
    "multiplier": "0.1",
    "units": "%RH",
    "description": "",
    "hw": "All",
    "category": "Permanent"
  },
  {
    "id": "8",
    "propname": "Authorized iButton",
    "bytes": "8",
    "type": "Unsigned",
    "min": "0",
    "max": "0xffffffffffffffff",
    "multiplier": "",
    "units": "",
    "description": "If ID is shown in this I/O that means that attached iButton is in iButton List",
    "hw": "FMB202 FMB204 FMB206",
    "category": "Permanent"
  },
  {
    "id": "4",
    "propname": "Pulse Counter Din1",
    "bytes": "4",
    "type": "Unsigned",
    "min": "0",
    "max": "4294967295",
    "multiplier": "",
    "units": "",
    "description": "Counts pulses count is reset when record is saved",
    "hw": "All",
    "category": "Permanent"
  },
  {
    "id": "5",
    "propname": "Pulse Counter Din2",
    "bytes": "4",
    "type": "Unsigned",
    "min": "0",
    "max": "4294967295",
    "multiplier": "",
    "units": "",
    "description": "Counts pulses count is reset when record is saved",
    "hw": "All",
    "category": "Permanent"
  },
  {
    "id": "7",
    "propname": "Records In Flash",
    "bytes": "2",
    "type": "Unsigned",
    "min": "0",
    "max": "65535",
    "multiplier": "",
    "units": "",
    "description": "Shows records count left in device memory.",
    "hw": "All",
    "category": "Permanent"
  },
  {
    "id": "30",
    "propname": "Number of DTC",
    "bytes": "1",
    "type": "Unsigned",
    "min": "0",
    "max": "255",
    "multiplier": "",
    "units": "",
    "description": "Number of DTC",
    "hw": "All",
    "category": "OBD"
  },
  {
    "id": "31",
    "propname": "Calculated engine load value",
    "bytes": "1",
    "type": "Unsigned",
    "min": "0",
    "max": "100",
    "multiplier": "",
    "units": "%",
    "description": "Calculated engine load value %",
    "hw": "All",
    "category": "OBD"
  },
  {
    "id": "32",
    "propname": "Engine coolant temperature",
    "bytes": "1",
    "type": "Signed",
    "min": "-128",
    "max": "127",
    "multiplier": "",
    "units": "°C",
    "description": "Engine coolant temperature °C",
    "hw": "All",
    "category": "OBD"
  },
  {
    "id": "33",
    "propname": "Short term fuel trim 1",
    "bytes": "1",
    "type": "Signed",
    "min": "-100",
    "max": "99",
    "multiplier": "",
    "units": "%",
    "description": "Short term fuel trim 1 %",
    "hw": "All",
    "category": "OBD"
  },
  {
    "id": "34",
    "propname": "Fuel pressure",
    "bytes": "2",
    "type": "Unsigned",
    "min": "0",
    "max": "765",
    "multiplier": "",
    "units": "kPa",
    "description": "Fuel pressure kPa",
    "hw": "All",
    "category": "OBD"
  },
  {
    "id": "35",
    "propname": "Intake manifold absolute pressure",
    "bytes": "1",
    "type": "Unsigned",
    "min": "0",
    "max": "255",
    "multiplier": "",
    "units": "kPa",
    "description": "Intake manifold absolute pressure kPa",
    "hw": "All",
    "category": "OBD"
  },
  {
    "id": "36",
    "propname": "Engine RPM",
    "bytes": "2",
    "type": "Unsigned",
    "min": "0",
    "max": "16384",
    "multiplier": "",
    "units": "rpm",
    "description": "Engine RPM rpm",
    "hw": "All",
    "category": "OBD"
  },
  {
    "id": "37",
    "propname": "Vehicle speed",
    "bytes": "1",
    "type": "Unsigned",
    "min": "0",
    "max": "255",
    "multiplier": "",
    "units": "km/h",
    "description": "Vehicle speed km/h",
    "hw": "All",
    "category": "OBD"
  },
  {
    "id": "38",
    "propname": "Timing advance",
    "bytes": "1",
    "type": "Signed",
    "min": "-64",
    "max": "64",
    "multiplier": "",
    "units": "°",
    "description": "Timing advance degrees °",
    "hw": "All",
    "category": "OBD"
  },
  {
    "id": "39",
    "propname": "Intake air temperature",
    "bytes": "1",
    "type": "Signed",
    "min": "-128",
    "max": "127",
    "multiplier": "",
    "units": "°C",
    "description": "Intake air temperature °C",
    "hw": "All",
    "category": "OBD"
  },
  {
    "id": "40",
    "propname": "MAF air flow rate",
    "bytes": "2",
    "type": "Unsigned",
    "min": "0",
    "max": "65535",
    "multiplier": "0.01",
    "units": "g/sec",
    "description": "MAF air flow rate g/sec",
    "hw": "All",
    "category": "OBD"
  },
  {
    "id": "41",
    "propname": "Throttle position",
    "bytes": "1",
    "type": "Unsigned",
    "min": "0",
    "max": "100",
    "multiplier": "",
    "units": "%",
    "description": "Throttle position %",
    "hw": "All",
    "category": "OBD"
  },
  {
    "id": "42",
    "propname": "Run time since engine start",
    "bytes": "2",
    "type": "Unsigned",
    "min": "0",
    "max": "65535",
    "multiplier": "",
    "units": "s",
    "description": "Run time since engine start s",
    "hw": "All",
    "category": "OBD"
  },
  {
    "id": "43",
    "propname": "Distance traveled MIL on",
    "bytes": "2",
    "type": "Unsigned",
    "min": "0",
    "max": "65535",
    "multiplier": "",
    "units": "km/h",
    "description": "Distance travelled MIL on km",
    "hw": "All",
    "category": "OBD"
  },
  {
    "id": "44",
    "propname": "Relative fuel rail pressure",
    "bytes": "2",
    "type": "Unsigned",
    "min": "0",
    "max": "5178",
    "multiplier": "0.1",
    "units": "kPa",
    "description": "Relative fuel rail pressure kPa",
    "hw": "All",
    "category": "OBD"
  },
  {
    "id": "45",
    "propname": "Direct fuel rail pressure",
    "bytes": "2",
    "type": "Unsigned",
    "min": "0",
    "max": "656",
    "multiplier": "0.1",
    "units": "kPa",
    "description": "Direct fuel rail pressure kPa",
    "hw": "All",
    "category": "OBD"
  },
  {
    "id": "46",
    "propname": "Commanded EGR",
    "bytes": "1",
    "type": "Unsigned",
    "min": "0",
    "max": "100",
    "multiplier": "",
    "units": "%",
    "description": "Commanded EGR %",
    "hw": "All",
    "category": "OBD"
  },
  {
    "id": "47",
    "propname": "EGR error",
    "bytes": "1",
    "type": "Signed",
    "min": "-100",
    "max": "100",
    "multiplier": "",
    "units": "%",
    "description": "EGR error %",
    "hw": "All",
    "category": "OBD"
  },
  {
    "id": "48",
    "propname": "Fuel level",
    "bytes": "1",
    "type": "Unsigned",
    "min": "0",
    "max": "100",
    "multiplier": "",
    "units": "%",
    "description": "Fuel level %",
    "hw": "All",
    "category": "OBD"
  },
  {
    "id": "49",
    "propname": "Distance travelled since codes cleared",
    "bytes": "2",
    "type": "Unsigned",
    "min": "0",
    "max": "65535",
    "multiplier": "",
    "units": "km/h",
    "description": "Distance travelled since codes cleared km",
    "hw": "All",
    "category": "OBD"
  },
  {
    "id": "50",
    "propname": "Barometric pressure",
    "bytes": "1",
    "type": "Unsigned",
    "min": "0",
    "max": "255",
    "multiplier": "",
    "units": "kPa",
    "description": "Barometric pressure kPa",
    "hw": "All",
    "category": "OBD"
  },
  {
    "id": "51",
    "propname": "Control module voltage",
    "bytes": "2",
    "type": "Unsigned",
    "min": "0",
    "max": "65535",
    "multiplier": "",
    "units": "mV",
    "description": "Control module voltage mV",
    "hw": "All",
    "category": "OBD"
  },
  {
    "id": "52",
    "propname": "Absolute load value",
    "bytes": "2",
    "type": "Unsigned",
    "min": "0",
    "max": "25700",
    "multiplier": "0.001",
    "units": "%",
    "description": "Absolute load value %",
    "hw": "All",
    "category": "OBD"
  },
  {
    "id": "53",
    "propname": "Ambient air temperature",
    "bytes": "1",
    "type": "Signed",
    "min": "-128",
    "max": "127",
    "multiplier": "",
    "units": "°C",
    "description": "Ambient air temperature °C",
    "hw": "All",
    "category": "OBD"
  },
  {
    "id": "54",
    "propname": "Time run with MIL on",
    "bytes": "2",
    "type": "Unsigned",
    "min": "0",
    "max": "65535",
    "multiplier": "",
    "units": "min",
    "description": "Time run with MIL on min",
    "hw": "All",
    "category": "OBD"
  },
  {
    "id": "55",
    "propname": "Time since trouble codes cleared",
    "bytes": "2",
    "type": "Unsigned",
    "min": "0",
    "max": "65535",
    "multiplier": "",
    "units": "min",
    "description": "Time since trouble codes cleared min",
    "hw": "All",
    "category": "OBD"
  },
  {
    "id": "56",
    "propname": "Absolute fuel rail pressure",
    "bytes": "2",
    "type": "Unsigned",
    "min": "0",
    "max": "65535",
    "multiplier": "0.1",
    "units": "kPa",
    "description": "Absolute fuel rail pressure kPa",
    "hw": "All",
    "category": "OBD"
  },
  {
    "id": "57",
    "propname": "Hybrid battery pack remaining life",
    "bytes": "1",
    "type": "Unsigned",
    "min": "0",
    "max": "100",
    "multiplier": "",
    "units": "%",
    "description": "Hybrid battery pack remaining life %",
    "hw": "All",
    "category": "OBD"
  },
  {
    "id": "58",
    "propname": "Engine oil temperature",
    "bytes": "1",
    "type": "Signed",
    "min": "-128",
    "max": "127",
    "multiplier": "",
    "units": "°C",
    "description": "Engine oil temperature °C",
    "hw": "All",
    "category": "OBD"
  },
  {
    "id": "59",
    "propname": "Fuel injection timing",
    "bytes": "2",
    "type": "Signed",
    "min": "-21000",
    "max": "30200",
    "multiplier": "0.01",
    "units": "°",
    "description": "Fuel injection timing degrees °",
    "hw": "All",
    "category": "OBD"
  },
  {
    "id": "60",
    "propname": "Engine fuel rate",
    "bytes": "2",
    "type": "Unsigned",
    "min": "0",
    "max": "32767",
    "multiplier": "0.01",
    "units": "l/100km",
    "description": "Engine fuel rate l/100km",
    "hw": "All",
    "category": "OBD"
  },
  {
    "id": "256",
    "propname": "VIN",
    "bytes": "17",
    "type": "String",
    "min": "0",
    "max": "255",
    "multiplier": "",
    "units": "",
    "description": "VIN number",
    "hw": "All",
    "category": "OBD"
  },
  {
    "id": "155",
    "propname": "Geofence zone 01",
    "bytes": "1",
    "type": "Unsigned",
    "min": "0",
    "max": "3",
    "multiplier": "",
    "units": "",
    "description": "Event: 0 – target left zone 1 – target entered zone 2 – over speeding end 3 – over speeding start",
    "hw": "All",
    "category": "Event"
  },
  {
    "id": "156",
    "propname": "Geofence zone 02",
    "bytes": "1",
    "type": "Unsigned",
    "min": "0",
    "max": "3",
    "multiplier": "",
    "units": "",
    "description": "Event: 0 – target left zone 1 – target entered zone 2 – over speeding end 3 – over speeding start",
    "hw": "All",
    "category": "Event"
  },
  {
    "id": "157",
    "propname": "Geofence zone 03",
    "bytes": "1",
    "type": "Unsigned",
    "min": "0",
    "max": "3",
    "multiplier": "",
    "units": "",
    "description": "Event: 0 – target left zone 1 – target entered zone 2 – over speeding end 3 – over speeding start",
    "hw": "All",
    "category": "Event"
  },
  {
    "id": "158",
    "propname": "Geofence zone 04",
    "bytes": "1",
    "type": "Unsigned",
    "min": "0",
    "max": "3",
    "multiplier": "",
    "units": "",
    "description": "Event: 0 – target left zone 1 – target entered zone 2 – over speeding end 3 – over speeding start",
    "hw": "All",
    "category": "Event"
  },
  {
    "id": "159",
    "propname": "Geofence zone 05",
    "bytes": "1",
    "type": "Unsigned",
    "min": "0",
    "max": "3",
    "multiplier": "",
    "units": "",
    "description": "Event: 0 – target left zone 1 – target entered zone 2 – over speeding end 3 – over speeding start",
    "hw": "All",
    "category": "Event"
  },
  {
    "id": "61",
    "propname": "Geofence zone 06",
    "bytes": "1",
    "type": "Unsigned",
    "min": "0",
    "max": "3",
    "multiplier": "",
    "units": "",
    "description": "Event: 0 – target left zone 1 – target entered zone 2 – over speeding end 3 – over speeding start",
    "hw": "All",
    "category": "Event"
  },
  {
    "id": "62",
    "propname": "Geofence zone 07",
    "bytes": "1",
    "type": "Unsigned",
    "min": "0",
    "max": "3",
    "multiplier": "",
    "units": "",
    "description": "Event: 0 – target left zone 1 – target entered zone 2 – over speeding end 3 – over speeding start",
    "hw": "All",
    "category": "Event"
  },
  {
    "id": "63",
    "propname": "Geofence zone 08",
    "bytes": "1",
    "type": "Unsigned",
    "min": "0",
    "max": "3",
    "multiplier": "",
    "units": "",
    "description": "Event: 0 – target left zone 1 – target entered zone 2 – over speeding end 3 – over speeding start",
    "hw": "All",
    "category": "Event"
  },
  {
    "id": "64",
    "propname": "Geofence zone 09",
    "bytes": "1",
    "type": "Unsigned",
    "min": "0",
    "max": "3",
    "multiplier": "",
    "units": "",
    "description": "Event: 0 – target left zone 1 – target entered zone 2 – over speeding end 3 – over speeding start",
    "hw": "All",
    "category": "Event"
  },
  {
    "id": "65",
    "propname": "Geofence zone 10",
    "bytes": "1",
    "type": "Unsigned",
    "min": "0",
    "max": "3",
    "multiplier": "",
    "units": "",
    "description": "Event: 0 – target left zone 1 – target entered zone 2 – over speeding end 3 – over speeding start",
    "hw": "All",
    "category": "Event"
  },
  {
    "id": "70",
    "propname": "Geofence zone 11",
    "bytes": "1",
    "type": "Unsigned",
    "min": "0",
    "max": "3",
    "multiplier": "",
    "units": "",
    "description": "Event: 0 – target left zone 1 – target entered zone 2 – over speeding end 3 – over speeding start",
    "hw": "All",
    "category": "Event"
  },
  {
    "id": "88",
    "propname": "Geofence zone 12",
    "bytes": "1",
    "type": "Unsigned",
    "min": "0",
    "max": "3",
    "multiplier": "",
    "units": "",
    "description": "Event: 0 – target left zone 1 – target entered zone 2 – over speeding end 3 – over speeding start",
    "hw": "All",
    "category": "Event"
  },
  {
    "id": "91",
    "propname": "Geofence zone 13",
    "bytes": "1",
    "type": "Unsigned",
    "min": "0",
    "max": "3",
    "multiplier": "",
    "units": "",
    "description": "Event: 0 – target left zone 1 – target entered zone 2 – over speeding end 3 – over speeding start",
    "hw": "All",
    "category": "Event"
  },
  {
    "id": "92",
    "propname": "Geofence zone 14",
    "bytes": "1",
    "type": "Unsigned",
    "min": "0",
    "max": "3",
    "multiplier": "",
    "units": "",
    "description": "Event: 0 – target left zone 1 – target entered zone 2 – over speeding end 3 – over speeding start",
    "hw": "All",
    "category": "Event"
  },
  {
    "id": "93",
    "propname": "Geofence zone 15",
    "bytes": "1",
    "type": "Unsigned",
    "min": "0",
    "max": "3",
    "multiplier": "",
    "units": "",
    "description": "Event: 0 – target left zone 1 – target entered zone 2 – over speeding end 3 – over speeding start",
    "hw": "All",
    "category": "Event"
  },
  {
    "id": "94",
    "propname": "Geofence zone 16",
    "bytes": "1",
    "type": "Unsigned",
    "min": "0",
    "max": "3",
    "multiplier": "",
    "units": "",
    "description": "Event: 0 – target left zone 1 – target entered zone 2 – over speeding end 3 – over speeding start",
    "hw": "All",
    "category": "Event"
  },
  {
    "id": "95",
    "propname": "Geofence zone 17",
    "bytes": "1",
    "type": "Unsigned",
    "min": "0",
    "max": "3",
    "multiplier": "",
    "units": "",
    "description": "Event: 0 – target left zone 1 – target entered zone 2 – over speeding end 3 – over speeding start",
    "hw": "All",
    "category": "Event"
  },
  {
    "id": "96",
    "propname": "Geofence zone 18",
    "bytes": "1",
    "type": "Unsigned",
    "min": "0",
    "max": "3",
    "multiplier": "",
    "units": "",
    "description": "Event: 0 – target left zone 1 – target entered zone 2 – over speeding end 3 – over speeding start",
    "hw": "All",
    "category": "Event"
  },
  {
    "id": "97",
    "propname": "Geofence zone 19",
    "bytes": "1",
    "type": "Unsigned",
    "min": "0",
    "max": "3",
    "multiplier": "",
    "units": "",
    "description": "Event: 0 – target left zone 1 – target entered zone 2 – over speeding end 3 – over speeding start",
    "hw": "All",
    "category": "Event"
  },
  {
    "id": "98",
    "propname": "Geofence zone 20",
    "bytes": "1",
    "type": "Unsigned",
    "min": "0",
    "max": "3",
    "multiplier": "",
    "units": "",
    "description": "Event: 0 – target left zone 1 – target entered zone 2 – over speeding end 3 – over speeding start",
    "hw": "All",
    "category": "Event"
  },
  {
    "id": "99",
    "propname": "Geofence zone 21",
    "bytes": "1",
    "type": "Unsigned",
    "min": "0",
    "max": "3",
    "multiplier": "",
    "units": "",
    "description": "Event: 0 – target left zone 1 – target entered zone 2 – over speeding end 3 – over speeding start",
    "hw": "All",
    "category": "Event"
  },
  {
    "id": "153",
    "propname": "Geofence zone 22",
    "bytes": "1",
    "type": "Unsigned",
    "min": "0",
    "max": "3",
    "multiplier": "",
    "units": "",
    "description": "Event: 0 – target left zone 1 – target entered zone 2 – over speeding end 3 – over speeding start",
    "hw": "All",
    "category": "Event"
  },
  {
    "id": "154",
    "propname": "Geofence zone 23",
    "bytes": "1",
    "type": "Unsigned",
    "min": "0",
    "max": "3",
    "multiplier": "",
    "units": "",
    "description": "Event: 0 – target left zone 1 – target entered zone 2 – over speeding end 3 – over speeding start",
    "hw": "All",
    "category": "Event"
  },
  {
    "id": "190",
    "propname": "Geofence zone 24",
    "bytes": "1",
    "type": "Unsigned",
    "min": "0",
    "max": "3",
    "multiplier": "",
    "units": "",
    "description": "Event: 0 – target left zone 1 – target entered zone 2 – over speeding end 3 – over speeding start",
    "hw": "All",
    "category": "Event"
  },
  {
    "id": "191",
    "propname": "Geofence zone 25",
    "bytes": "1",
    "type": "Unsigned",
    "min": "0",
    "max": "3",
    "multiplier": "",
    "units": "",
    "description": "Event: 0 – target left zone 1 – target entered zone 2 – over speeding end 3 – over speeding start",
    "hw": "All",
    "category": "Event"
  },
  {
    "id": "192",
    "propname": "Geofence zone 26",
    "bytes": "1",
    "type": "Unsigned",
    "min": "0",
    "max": "3",
    "multiplier": "",
    "units": "",
    "description": "Event: 0 – target left zone 1 – target entered zone 2 – over speeding end 3 – over speeding start",
    "hw": "All",
    "category": "Event"
  },
  {
    "id": "193",
    "propname": "Geofence zone 27",
    "bytes": "1",
    "type": "Unsigned",
    "min": "0",
    "max": "3",
    "multiplier": "",
    "units": "",
    "description": "Event: 0 – target left zone 1 – target entered zone 2 – over speeding end 3 – over speeding start",
    "hw": "All",
    "category": "Event"
  },
  {
    "id": "194",
    "propname": "Geofence zone 28",
    "bytes": "1",
    "type": "Unsigned",
    "min": "0",
    "max": "3",
    "multiplier": "",
    "units": "",
    "description": "Event: 0 – target left zone 1 – target entered zone 2 – over speeding end 3 – over speeding start",
    "hw": "All",
    "category": "Event"
  },
  {
    "id": "195",
    "propname": "Geofence zone 29",
    "bytes": "1",
    "type": "Unsigned",
    "min": "0",
    "max": "3",
    "multiplier": "",
    "units": "",
    "description": "Event: 0 – target left zone 1 – target entered zone 2 – over speeding end 3 – over speeding start",
    "hw": "All",
    "category": "Event"
  },
  {
    "id": "196",
    "propname": "Geofence zone 30",
    "bytes": "1",
    "type": "Unsigned",
    "min": "0",
    "max": "3",
    "multiplier": "",
    "units": "",
    "description": "Event: 0 – target left zone 1 – target entered zone 2 – over speeding end 3 – over speeding start",
    "hw": "All",
    "category": "Event"
  },
  {
    "id": "197",
    "propname": "Geofence zone 31",
    "bytes": "1",
    "type": "Unsigned",
    "min": "0",
    "max": "3",
    "multiplier": "",
    "units": "",
    "description": "Event: 0 – target left zone 1 – target entered zone 2 – over speeding end 3 – over speeding start",
    "hw": "All",
    "category": "Event"
  },
  {
    "id": "198",
    "propname": "Geofence zone 32",
    "bytes": "1",
    "type": "Unsigned",
    "min": "0",
    "max": "3",
    "multiplier": "",
    "units": "",
    "description": "Event: 0 – target left zone 1 – target entered zone 2 – over speeding end 3 – over speeding start",
    "hw": "All",
    "category": "Event"
  },
  {
    "id": "208",
    "propname": "Geofence zone 33",
    "bytes": "1",
    "type": "Unsigned",
    "min": "0",
    "max": "3",
    "multiplier": "",
    "units": "",
    "description": "Event: 0 – target left zone 1 – target entered zone 2 – over speeding end 3 – over speeding start",
    "hw": "All",
    "category": "Event"
  },
  {
    "id": "209",
    "propname": "Geofence zone 34",
    "bytes": "1",
    "type": "Unsigned",
    "min": "0",
    "max": "3",
    "multiplier": "",
    "units": "",
    "description": "Event: 0 – target left zone 1 – target entered zone 2 – over speeding end 3 – over speeding start",
    "hw": "All",
    "category": "Event"
  },
  {
    "id": "216",
    "propname": "Geofence zone 35",
    "bytes": "1",
    "type": "Unsigned",
    "min": "0",
    "max": "3",
    "multiplier": "",
    "units": "",
    "description": "Event: 0 – target left zone 1 – target entered zone 2 – over speeding end 3 – over speeding start",
    "hw": "All",
    "category": "Event"
  },
  {
    "id": "217",
    "propname": "Geofence zone 36",
    "bytes": "1",
    "type": "Unsigned",
    "min": "0",
    "max": "3",
    "multiplier": "",
    "units": "",
    "description": "Event: 0 – target left zone 1 – target entered zone 2 – over speeding end 3 – over speeding start",
    "hw": "All",
    "category": "Event"
  },
  {
    "id": "218",
    "propname": "Geofence zone 37",
    "bytes": "1",
    "type": "Unsigned",
    "min": "0",
    "max": "3",
    "multiplier": "",
    "units": "",
    "description": "Event: 0 – target left zone 1 – target entered zone 2 – over speeding end 3 – over speeding start",
    "hw": "All",
    "category": "Event"
  },
  {
    "id": "219",
    "propname": "Geofence zone 38",
    "bytes": "1",
    "type": "Unsigned",
    "min": "0",
    "max": "3",
    "multiplier": "",
    "units": "",
    "description": "Event: 0 – target left zone 1 – target entered zone 2 – over speeding end 3 – over speeding start",
    "hw": "All",
    "category": "Event"
  },
  {
    "id": "220",
    "propname": "Geofence zone 39",
    "bytes": "1",
    "type": "Unsigned",
    "min": "0",
    "max": "3",
    "multiplier": "",
    "units": "",
    "description": "Event: 0 – target left zone 1 – target entered zone 2 – over speeding end 3 – over speeding start",
    "hw": "All",
    "category": "Event"
  },
  {
    "id": "221",
    "propname": "Geofence zone 40",
    "bytes": "1",
    "type": "Unsigned",
    "min": "0",
    "max": "3",
    "multiplier": "",
    "units": "",
    "description": "Event: 0 – target left zone 1 – target entered zone 2 – over speeding end 3 – over speeding start",
    "hw": "All",
    "category": "Event"
  },
  {
    "id": "222",
    "propname": "Geofence zone 41",
    "bytes": "1",
    "type": "Unsigned",
    "min": "0",
    "max": "3",
    "multiplier": "",
    "units": "",
    "description": "Event: 0 – target left zone 1 – target entered zone 2 – over speeding end 3 – over speeding start",
    "hw": "All",
    "category": "Event"
  },
  {
    "id": "223",
    "propname": "Geofence zone 42",
    "bytes": "1",
    "type": "Unsigned",
    "min": "0",
    "max": "3",
    "multiplier": "",
    "units": "",
    "description": "Event: 0 – target left zone 1 – target entered zone 2 – over speeding end 3 – over speeding start",
    "hw": "All",
    "category": "Event"
  },
  {
    "id": "224",
    "propname": "Geofence zone 43",
    "bytes": "1",
    "type": "Unsigned",
    "min": "0",
    "max": "3",
    "multiplier": "",
    "units": "",
    "description": "Event: 0 – target left zone 1 – target entered zone 2 – over speeding end 3 – over speeding start",
    "hw": "All",
    "category": "Event"
  },
  {
    "id": "225",
    "propname": "Geofence zone 44",
    "bytes": "1",
    "type": "Unsigned",
    "min": "0",
    "max": "3",
    "multiplier": "",
    "units": "",
    "description": "Event: 0 – target left zone 1 – target entered zone 2 – over speeding end 3 – over speeding start",
    "hw": "All",
    "category": "Event"
  },
  {
    "id": "226",
    "propname": "Geofence zone 45",
    "bytes": "1",
    "type": "Unsigned",
    "min": "0",
    "max": "3",
    "multiplier": "",
    "units": "",
    "description": "Event: 0 – target left zone 1 – target entered zone 2 – over speeding end 3 – over speeding start",
    "hw": "All",
    "category": "Event"
  },
  {
    "id": "227",
    "propname": "Geofence zone 46",
    "bytes": "1",
    "type": "Unsigned",
    "min": "0",
    "max": "3",
    "multiplier": "",
    "units": "",
    "description": "Event: 0 – target left zone 1 – target entered zone 2 – over speeding end 3 – over speeding start",
    "hw": "All",
    "category": "Event"
  },
  {
    "id": "228",
    "propname": "Geofence zone 47",
    "bytes": "1",
    "type": "Unsigned",
    "min": "0",
    "max": "3",
    "multiplier": "",
    "units": "",
    "description": "Event: 0 – target left zone 1 – target entered zone 2 – over speeding end 3 – over speeding start",
    "hw": "All",
    "category": "Event"
  },
  {
    "id": "229",
    "propname": "Geofence zone 48",
    "bytes": "1",
    "type": "Unsigned",
    "min": "0",
    "max": "3",
    "multiplier": "",
    "units": "",
    "description": "Event: 0 – target left zone 1 – target entered zone 2 – over speeding end 3 – over speeding start",
    "hw": "All",
    "category": "Event"
  },
  {
    "id": "230",
    "propname": "Geofence zone 49",
    "bytes": "1",
    "type": "Unsigned",
    "min": "0",
    "max": "3",
    "multiplier": "",
    "units": "",
    "description": "Event: 0 – target left zone 1 – target entered zone 2 – over speeding end 3 – over speeding start",
    "hw": "All",
    "category": "Event"
  },
  {
    "id": "231",
    "propname": "Geofence zone 50",
    "bytes": "1",
    "type": "Unsigned",
    "min": "0",
    "max": "3",
    "multiplier": "",
    "units": "",
    "description": "Event: 0 – target left zone 1 – target entered zone 2 – over speeding end 3 – over speeding start",
    "hw": "All",
    "category": "Event"
  },
  {
    "id": "175",
    "propname": "Auto Geofence",
    "bytes": "1",
    "type": "Unsigned",
    "min": "0",
    "max": "1",
    "multiplier": "",
    "units": "",
    "description": "Event: 0 – target left zone 1 – target entered zone",
    "hw": "All",
    "category": "Event"
  },
  {
    "id": "250",
    "propname": "Trip",
    "bytes": "1",
    "type": "Unsigned",
    "min": "0",
    "max": "9",
    "multiplier": "",
    "units": "",
    "description": "0 – trip stop 1 – trip start 2 – Business Status; 3 – Private Status; 4-9 – Custom Statuses",
    "hw": "All",
    "category": "Event"
  },
  {
    "id": "255",
    "propname": "Over Speeding",
    "bytes": "1",
    "type": "Unsigned",
    "min": "0",
    "max": "255",
    "multiplier": "",
    "units": "km/h",
    "description": "At over speeding start km/h at over speeding end km/h",
    "hw": "All",
    "category": "Event"
  },
  {
    "id": "251",
    "propname": "Idling",
    "bytes": "1",
    "type": "Unsigned",
    "min": "0",
    "max": "1",
    "multiplier": "",
    "units": "",
    "description": "0 – moving 1 – idling",
    "hw": "All",
    "category": "Event"
  },
  {
    "id": "253",
    "propname": "Green driving type",
    "bytes": "1",
    "type": "Unsigned",
    "min": "1",
    "max": "3",
    "multiplier": "",
    "units": "",
    "description": "1 – harsh acceleration 2 – harsh braking 3 – harsh cornering",
    "hw": "All",
    "category": "Event"
  },
  {
    "id": "246",
    "propname": "Towing",
    "bytes": "1",
    "type": "Unsigned",
    "min": "0",
    "max": "1",
    "multiplier": "",
    "units": "",
    "description": "0 – steady 1 – towing",
    "hw": "All",
    "category": "Event"
  },
  {
    "id": "252",
    "propname": "Unplug",
    "bytes": "1",
    "type": "Unsigned",
    "min": "0",
    "max": "1",
    "multiplier": "",
    "units": "",
    "description": "0 – battery present 1 – battery unpluged",
    "hw": "All",
    "category": "Event"
  },
  {
    "id": "247",
    "propname": "Crash detection",
    "bytes": "1",
    "type": "Unsigned",
    "min": "0",
    "max": "1",
    "multiplier": "",
    "units": "",
    "description": "0 – no crash 1 – crash",
    "hw": "All",
    "category": "Event"
  },
  {
    "id": "248",
    "propname": "Immobilizer",
    "bytes": "1",
    "type": "Unsigned",
    "min": "0",
    "max": "2",
    "multiplier": "",
    "units": "",
    "description": "0 – iButton not connected 1 – iButton connected (Immobilizer) 2 – iButton connected (Authorized Driving)",
    "hw": "All",
    "category": "Event"
  },
  {
    "id": "254",
    "propname": "Green driving value",
    "bytes": "1",
    "type": "Unsigned",
    "min": "0",
    "max": "255",
    "multiplier": "acc and braking: 0.01",
    "units": "G or rad",
    "description": "Depending on green driving type: if harsh acceleration or braking – g*100 (value 123 -> 1.23g) if harsh cornering – degrees (value in radians)",
    "hw": "All",
    "category": "Event"
  },
  {
    "id": "249",
    "propname": "Jamming",
    "bytes": "1",
    "type": "Unsigned",
    "min": "0",
    "max": "1",
    "multiplier": "",
    "units": "",
    "description": "0 – jamming stop1 – jamming start",
    "hw": "All",
    "category": "Event"
  },
  {
    "id": "14",
    "propname": "ICCID2",
    "bytes": "8",
    "type": "Unsigned",
    "min": "0",
    "max": "0xffffffffffffffff",
    "multiplier": "",
    "units": "",
    "description": "Value of SIM ICCID LSB",
    "hw": "All",
    "category": "Event"
  },
  {
    "id": "243",
    "propname": "Green driving event duration",
    "bytes": "2",
    "type": "Unsigned",
    "min": "0",
    "max": "65535",
    "multiplier": "",
    "units": "ms",
    "description": "Duration of event that did generate Green Driving",
    "hw": "All",
    "category": "Event"
  },
  {
    "id": "244",
    "propname": "DIN2/AIN2 spec event",
    "bytes": "1",
    "type": "Unsigned",
    "min": "0",
    "max": "1",
    "multiplier": "",
    "units": "",
    "description": "Generates after spec DIN2/AIN2 scenario",
    "hw": "FMB207",
    "category": "Event"
  },
  {
    "id": "109",
    "propname": "Delimiter",
    "bytes": "Variable",
    "type": "Hex",
    "min": "0",
    "max": "254",
    "multiplier": "",
    "units": "",
    "description": "Packet received on RS232",
    "hw": "FMB207",
    "category": "Event"
  }
]
